export const CUSTOMERS_URL = 'http://localhost:4000/customers'; // tugri
export const STORAGE_URL = 'http://localhost:4000/storage'; // products -- tugirladim
export const STAFF_URL = 'http://localhost:4000/staff'; // tugri
export const ORDERS_URL = 'http://localhost:4000/orders'; // tugri
export const CALCULATE_URL = 'http://localhost:4000/calculation'; // tugri tugirladim
export const DAILY_TASKS_URL = 'http://localhost:4000/daily-tasks'; // tugri - kunlik ish - tugirladim
export const SALE_URL = 'http://localhost:4000/sale'; // tugri - tugirladim sail edi 
export const NASIYA_URL = 'http://localhost:4000/nasiya'; // tugri - tugirladim  debt edi
export const EXPENSES_URL = 'http://localhost:4000/expenses'; // tugri - tugirladim outputs edi
export const DAROMAT_URL = 'http://localhost:4000/daromat'; // tugri - tugirladim
export const PLANS_URL = 'http://localhost:4000/plans';
export const XAMKOR_URL = 'http://localhost:4000/xamkorlar';